# Project: 项目1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = ../../../../高程作业/17-b1/17-b1-main.o ../../../../高程作业/17-b1/17-b1-TString.o ../../../../高程作业/17-b1/17-b1-TStringAdv.o
LINKOBJ  = ../../../../高程作业/17-b1/17-b1-main.o ../../../../高程作业/17-b1/17-b1-TString.o ../../../../高程作业/17-b1/17-b1-TStringAdv.o
LIBS     = -static-libgcc -m32 -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../../../../高程作业/17-b1/17-b1-main.o: ../../../../高程作业/17-b1/17-b1-main.cpp
	$(CPP) -c ../../../../高程作业/17-b1/17-b1-main.cpp -o ../../../../高程作业/17-b1/17-b1-main.o $(CXXFLAGS)

../../../../高程作业/17-b1/17-b1-TString.o: ../../../../高程作业/17-b1/17-b1-TString.cpp
	$(CPP) -c ../../../../高程作业/17-b1/17-b1-TString.cpp -o ../../../../高程作业/17-b1/17-b1-TString.o $(CXXFLAGS)

../../../../高程作业/17-b1/17-b1-TStringAdv.o: ../../../../高程作业/17-b1/17-b1-TStringAdv.cpp
	$(CPP) -c ../../../../高程作业/17-b1/17-b1-TStringAdv.cpp -o ../../../../高程作业/17-b1/17-b1-TStringAdv.o $(CXXFLAGS)
